import { GalleryImage } from "@/types";

export const galleryImages: GalleryImage[] = [
  {
    id: 1,
    thumb: "/LuckMC/spawngenel.avif",
    src: "/LuckMC/spawngenel.avif",
    alt: "Skyblock Sunucusu genel spawn görünümü",
    caption: "Genel Spawn Görünümü",
  },
  {
    id: 2,
    thumb: "/LuckMC/spawn.avif",
    src: "/LuckMC/spawn.avif",
    alt: "Skyblock Sunucusu spawn noktası",
    caption: "Spawn",
  },
  {
    id: 3,
    thumb: "/LuckMC/avantajlar.avif",
    src: "/LuckMC/avantajlar.avif",
    alt: "Skyblock sunucusundaki avantajlar menüsü",
    caption: "Avantajlar",
  },
  {
    id: 4,
    thumb: "/LuckMC/hizlierisim.avif",
    src: "/LuckMC/hizlierisim.avif",
    alt: "Skyblock sunucusundaki hızlı erişim menüsü",
    caption: "Hızlı Erişim",
  },
  {
    id: 5,
    thumb: "/LuckMC/koylutakas.avif",
    src: "/LuckMC/koylutakas.avif",
    alt: "Skyblock sunucusundaki köylü takas sistemi",
    caption: "Köylü Takas",
  },
  {
    id: 6,
    thumb: "/LuckMC/balikci.avif",
    src: "/LuckMC/balikci.avif",
    alt: "Skyblock sunucusundaki balıkçı",
    caption: "Balıkçı",
  },
  {
    id: 7,
    thumb: "/LuckMC/metintasi.avif",
    src: "/LuckMC/metintasi.avif",
    alt: "Skyblock sunucusundaki metin taşı",
    caption: "Metin Taşı",
  },
  {
    id: 8,
    thumb: "/LuckMC/ada1.avif",
    src: "/LuckMC/ada1.avif",
    alt: "Skyblock ada görünümü 1",
    caption: "Ada 1",
  },
  {
    id: 9,
    thumb: "/LuckMC/ada2.avif",
    src: "/LuckMC/ada2.avif",
    alt: "Skyblock ada görünümü 2",
    caption: "Ada 2",
  },
  {
    id: 10,
    thumb: "/LuckMC/adatabela.avif",
    src: "/LuckMC/adatabela.avif",
    alt: "Skyblock sunucusundaki ada tabelası",
    caption: "Ada Tabelası",
  },
  {
    id: 11,
    thumb: "/LuckMC/barci.avif",
    src: "/LuckMC/barci.avif",
    alt: "Skyblock sunucusundaki barcı",
    caption: "Barcı",
  },
  {
    id: 12,
    thumb: "/LuckMC/kasa1.avif",
    src: "/LuckMC/kasa1.avif",
    alt: "Skyblock sunucusundaki kasa 1",
    caption: "Kasa 1",
  },
  {
    id: 13,
    thumb: "/LuckMC/kasa2.avif",
    src: "/LuckMC/kasa2.avif",
    alt: "Skyblock sunucusundaki kasa 2",
    caption: "Kasa 2",
  },
];